# Generated by Django 2.0.6 on 2018-10-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitreps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitreps',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='sitreps',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
