# Generated by Django 2.0.6 on 2018-10-01 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitreps', '0002_auto_20181001_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitreps',
            name='text',
        ),
        migrations.RemoveField(
            model_name='sitreps',
            name='title',
        ),
    ]
