# Generated by Django 2.0.6 on 2018-10-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitreps', '0003_auto_20181001_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitreps',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sitreps',
            name='title',
            field=models.CharField(default='SITREP', max_length=200),
        ),
    ]
