# Generated by Django 2.0.6 on 2018-10-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitreps', '0004_auto_20181001_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitreps',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='pub date'),
        ),
    ]
