# Generated by Django 2.0.6 on 2018-10-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitreps', '0005_auto_20181001_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitreps',
            name='pub_date',
            field=models.DateTimeField(verbose_name='pub date'),
        ),
        migrations.AlterField(
            model_name='sitreps',
            name='title',
            field=models.CharField(default='SITREP 2018-10-01', max_length=200),
        ),
    ]
