# Generated by Django 2.0.6 on 2018-10-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitreps', '0008_sitreps_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitreps',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='text'),
        ),
    ]
