# Generated by Django 2.0.6 on 2018-10-02 20:37

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitreps', '0011_auto_20181002_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitreps',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='text'),
        ),
    ]
