# Generated by Django 2.0.6 on 2018-10-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitreps', '0012_auto_20181002_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitreps',
            name='title',
            field=models.CharField(default='SITREP 2018-10-03', max_length=200),
        ),
    ]
