# Generated by Django 2.1.2 on 2018-10-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitreps', '0013_auto_20181003_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitreps',
            name='title',
            field=models.CharField(default='SITREP 2018-10-05', max_length=200),
        ),
    ]
